---
title: "Education"
---

<div style="margin-top:50px;">
</div>

```{r "setup", include = FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/Harrison Kirby/Desktop/GLP/ccu18")
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.showtext=TRUE)
```

```{r libraries}
#Data
library(survey)
library(tidyverse)
library(magrittr)
library(feather)
library(labelled)

#Graphing
library(ggthemes)
library(classInt)
library(showtext)
library(reshape2)
library(plotly)
library(wesanderson)
library(kableExtra)
library(scales)

#Mapping
library(rgdal)
library(RColorBrewer)
library(leaflet)

#Make the dplyr select function the default over the plotly select function
select <- function(...){dplyr::select(...)}
```

```{r functions}
source('helper_functions.R')
```

```{r graphing}
source('graphing_functions.R')

font_add("Museo Sans 300", "MuseoSans_300.otf")
font_add("Museo Sans 300 Italic", "MuseoSans_300_Italic.otf")

#Tract Map
map_jc = readOGR('data/maps/tract', layer = "JC Tracts",
                 GDAL1_integer64_policy = TRUE, stringsAsFactors = FALSE, verbose = FALSE)

map_jc$TRACT <- as.numeric(map_jc$TRACT)

nh_names <- read_csv('data/maps/tract_to_nh.csv')

nh_names$Id2 <- substr(nh_names$Id2, 6, 13)
nh_names$Id2 <- as.numeric(nh_names$Id2)

map_jc@data <- full_join(map_jc@data, nh_names, by = c('TRACT' = 'Id2'))

map_jc@data$l_line1 <- paste("Tract #:", map_jc@data$TRACT, "in the")
map_jc@data$l_line2 <- paste(map_jc@data$Neighborhood, "neighborhood")

rm(nh_names)

#Zip Code map
map_jc_zip = readOGR('data/maps/zip', layer = 'Jefferson_County_KY_ZIP_Codes',
                     GDAL1_integer64_policy = TRUE, stringsAsFactors = FALSE, verbose = FALSE)

map_jc_zip$ZIPCODE <- as.numeric(map_jc_zip$ZIPCODE)

map_jc_zip@data$l_line1 <- paste0("Zip Code ", map_jc_zip@data$ZIPCODE)
```

```{r Website / output toggle}
web = TRUE
```

<div style="margin-top:50px;">
</div>
# Bachelor Degree or Higher, Age 25 to 64
                 
## Ranking

```{r data1}
degree_df <- acs_time("/data/education/B15001/")

degree_df %<>%
  mutate(
    num_25_34 = 
      `Estimate; Male: - 25 to 34 years:` +
      `Estimate; Female: - 25 to 34 years:`,
    num_25_64 = 
      `Estimate; Male: - 25 to 34 years:` +
      `Estimate; Male: - 35 to 44 years:` +
      `Estimate; Male: - 45 to 64 years:` +
      `Estimate; Female: - 25 to 34 years:` +
      `Estimate; Female: - 35 to 44 years:` +
      `Estimate; Female: - 45 to 64 years:`,
    
    num_25_34_grad = 
      `Estimate; Male: - 25 to 34 years: - Graduate or professional degree` + 
      `Estimate; Female: - 25 to 34 years: - Graduate or professional degree`,
    
    num_25_64_grad = 
      `Estimate; Male: - 25 to 34 years: - Graduate or professional degree` +
      `Estimate; Male: - 35 to 44 years: - Graduate or professional degree` +
      `Estimate; Male: - 45 to 64 years: - Graduate or professional degree` +
      `Estimate; Female: - 25 to 34 years: - Graduate or professional degree` +
      `Estimate; Female: - 35 to 44 years: - Graduate or professional degree` +
      `Estimate; Female: - 45 to 64 years: - Graduate or professional degree`,
    
    num_25_34_bach_plus = 
      `Estimate; Male: - 25 to 34 years: - Bachelor's degree` + 
      `Estimate; Female: - 25 to 34 years: - Bachelor's degree` +
      num_25_34_grad,
    
    num_25_64_bach_plus = 
      `Estimate; Male: - 25 to 34 years: - Bachelor's degree` +
      `Estimate; Male: - 35 to 44 years: - Bachelor's degree` +
      `Estimate; Male: - 45 to 64 years: - Bachelor's degree` +
      `Estimate; Female: - 25 to 34 years: - Bachelor's degree` +
      `Estimate; Female: - 35 to 44 years: - Bachelor's degree` +
      `Estimate; Female: - 45 to 64 years: - Bachelor's degree` +
      num_25_64_grad,
    
    num_25_34_assoc_plus = 
      `Estimate; Male: - 25 to 34 years: - Associate's degree` +
      `Estimate; Female: - 25 to 34 years: - Associate's degree` +
      num_25_34_bach_plus,
    
    num_25_64_assoc_plus = 
      `Estimate; Male: - 25 to 34 years: - Associate's degree` +
      `Estimate; Male: - 35 to 44 years: - Associate's degree` +
      `Estimate; Male: - 45 to 64 years: - Associate's degree` +
      `Estimate; Female: - 25 to 34 years: - Associate's degree` +
      `Estimate; Female: - 35 to 44 years: - Associate's degree` +
      `Estimate; Female: - 45 to 64 years: - Associate's degree` +
      num_25_64_bach_plus,
    
    per_25_34_assoc_plus = num_25_34_assoc_plus / num_25_34 * 100,
    per_25_64_assoc_plus = num_25_64_assoc_plus / num_25_64 * 100,
    
    per_25_34_bach_plus = num_25_34_bach_plus / num_25_34 * 100,
    per_25_64_bach_plus = num_25_64_bach_plus / num_25_64 * 100,
    
    per_25_34_grad = num_25_34_grad / num_25_34 * 100,
    per_25_64_grad = num_25_64_grad / num_25_64 * 100) %>%
    {
      x <- .
      full_join(
        x %>% weight_stl(c('per_25_34_assoc_plus', 'per_25_34_bach_plus', 'per_25_34_grad'), 'num_25_34'),
        x %>% weight_stl(c('per_25_64_assoc_plus', 'per_25_64_bach_plus', 'per_25_64_grad'), 'num_25_64'))
    }

data <- degree_df

data %<>% pull_peers_FIPS() %>% select(FIPS, city, year, current, baseline, everything())

rm(degree_df)
```

```{r graph1}
rank_and_nb_group(data[data$year == 2016,], 
                  'per_25_64_bach_plus', 
                  plot_title = 'Bachelor Degrees or Higher, 2016',
                  subtitle_text = 'Ages 25-64')
```

## Trendline {.tabset}
```{r data2, fig.width = 10}
#White
degree_white_05 <- acs_time("/data/education/B15002H/Y05/", starting_year = 2005)
degree_white_08 <- acs_time("/data/education/B15002H/Y08/", starting_year = 2008)

degree_white_05 <- degree_white_05 %>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_white =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_white = 
        (`Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100) %>%
  select(FIPS, year, assoc_plus_per_white, bach_plus_per_white, total)

degree_white_08 <- degree_white_08 %>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_white =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_white = 
        (`Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
         /total * 100) %>%
  select(FIPS, year, assoc_plus_per_white, bach_plus_per_white, total)

degree_white <- bind_rows(degree_white_05, degree_white_08) %>%
  weight_stl(c('assoc_plus_per_white', 'bach_plus_per_white'), 'total')

#Black
degree_black_05 = acs_time("/data/education/B15002B/Y05/", starting_year = 2005)
degree_black_08 = acs_time("/data/education/B15002B/Y08/", starting_year = 2008)

degree_black_05 %<>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_black =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_black = 
        (`Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        /total * 100) %>%
  select(FIPS, year, assoc_plus_per_black, bach_plus_per_black, total)

degree_black_08 %<>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_black =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_black = 
        (`Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        /total * 100) %>% 
  select(FIPS, year, assoc_plus_per_black, bach_plus_per_black, total)

degree_black = bind_rows(degree_black_05, degree_black_08) %>%
  weight_stl(c('assoc_plus_per_black', 'bach_plus_per_black'), 'total')

#Hispanic
degree_hispanic_05 = acs_time("/data/education/B15002I/Y05/", starting_year = 2005)
degree_hispanic_08 = acs_time("/data/education/B15002I/Y08/", starting_year = 2008)

degree_hispanic_05 = degree_hispanic_05 %>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_hispanic =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_hispanic = 
      (`Estimate; Female: - Bachelor's degree` + 
       `Estimate; Male: - Bachelor's degree` + 
       `Estimate; Female: - Graduate degree` + 
       `Estimate; Male: - Graduate degree`)
      /total * 100) %>%
  select(FIPS, year, assoc_plus_per_hispanic, bach_plus_per_hispanic, total)

degree_hispanic_08 = degree_hispanic_08 %>%
  mutate(
    total = `Estimate; Total:`,
    
    assoc_plus_per_hispanic =
        (`Estimate; Female: - Associate's degree` +
        `Estimate; Male: - Associate's degree` +
        `Estimate; Female: - Bachelor's degree` + 
        `Estimate; Male: - Bachelor's degree` + 
        `Estimate; Female: - Graduate degree` + 
        `Estimate; Male: - Graduate degree`)
        / total * 100,
    
    bach_plus_per_hispanic = 
      (`Estimate; Female: - Bachelor's degree` + 
       `Estimate; Male: - Bachelor's degree` + 
       `Estimate; Female: - Graduate degree` + 
       `Estimate; Male: - Graduate degree`)
      /total * 100) %>%
  select(FIPS, year, assoc_plus_per_hispanic, bach_plus_per_hispanic, total)

degree_hispanic = bind_rows(degree_hispanic_05, degree_hispanic_08) %>%
  weight_stl(c('assoc_plus_per_hispanic', 'bach_plus_per_hispanic'), 'total')

data %<>% bind_df(degree_white, degree_black, degree_hispanic)

rm(degree_white_05, degree_white_08, degree_white, degree_black_05, degree_black_08, degree_black, degree_hispanic_05, degree_hispanic_08, degree_hispanic)
```

### Overall
```{r graph2.1}
graph_trendline(data,
                'per_25_64_bach_plus',
                plot_title = 'Bachelor Degrees, Ages 25-64',
                rollmean = 3)
```

### By Ethnicity
```{r graph2.2}
graph_df <- data%>%
filter(FIPS == 21111)%>%
  select(year, bach_plus_per_white, bach_plus_per_black, bach_plus_per_hispanic) %>%
  mutate_at(vars(bach_plus_per_white, bach_plus_per_black, bach_plus_per_hispanic), rollmean3) %>%
  gather(bach_plus_per_white:bach_plus_per_hispanic, 
         key = "var", value = "value")%>%
  arrange(var)

graph_df$var <- factor(graph_df$var, levels = unique(graph_df$var))

graph_trendline_race(
  graph_df,
  xmin = 2006,
  xmax = 2015,
  plot_title = "Bachelor Degrees by Ethnicity, Ages 25-64",
  subtitle_text = '3-year rolling average',
  labels = c("African American", "Hispanic", "White"),
  y_title = "Percent",
  color_pal = wes_palette("Moonrise2"))
```

```{r graph2.3, eval = FALSE}
graph_trendline_race_peer(data, 
                          vars = c('bach_plus_per_white', 'bach_plus_per_black', 'bach_plus_per_hispanic'),
                          plot_title = 'Bachelor Degrees by Ethnicity',
                          subtitle_text = 'Ages 25-64',
                          rollmean = 5)
```

## Map
```{r data3}
degree_map <- read_csv('Data/Education/ACS_16_5YR_B15001_with_ann.csv', skip = 1)

degree_map %<>%
  mutate(
    num_25_34 = 
      `Estimate; Male: - 25 to 34 years:` +
      `Estimate; Female: - 25 to 34 years:`,
    num_25_64 = 
      `Estimate; Male: - 25 to 34 years:` +
      `Estimate; Male: - 35 to 44 years:` +
      `Estimate; Male: - 45 to 64 years:` +
      `Estimate; Female: - 25 to 34 years:` +
      `Estimate; Female: - 35 to 44 years:` +
      `Estimate; Female: - 45 to 64 years:`,
    
    num_25_34_grad = 
      `Estimate; Male: - 25 to 34 years: - Graduate or professional degree` + 
      `Estimate; Female: - 25 to 34 years: - Graduate or professional degree`,
    
    num_25_64_grad = 
      `Estimate; Male: - 25 to 34 years: - Graduate or professional degree` +
      `Estimate; Male: - 35 to 44 years: - Graduate or professional degree` +
      `Estimate; Male: - 45 to 64 years: - Graduate or professional degree` +
      `Estimate; Female: - 25 to 34 years: - Graduate or professional degree` +
      `Estimate; Female: - 35 to 44 years: - Graduate or professional degree` +
      `Estimate; Female: - 45 to 64 years: - Graduate or professional degree`,
    
    num_25_34_bach_plus = 
      `Estimate; Male: - 25 to 34 years: - Bachelor's degree` + 
      `Estimate; Female: - 25 to 34 years: - Bachelor's degree` +
      num_25_34_grad,
    
    num_25_64_bach_plus = 
      `Estimate; Male: - 25 to 34 years: - Bachelor's degree` +
      `Estimate; Male: - 35 to 44 years: - Bachelor's degree` +
      `Estimate; Male: - 45 to 64 years: - Bachelor's degree` +
      `Estimate; Female: - 25 to 34 years: - Bachelor's degree` +
      `Estimate; Female: - 35 to 44 years: - Bachelor's degree` +
      `Estimate; Female: - 45 to 64 years: - Bachelor's degree` +
      num_25_64_grad,
    
    num_25_34_assoc_plus = 
      `Estimate; Male: - 25 to 34 years: - Associate's degree` +
      `Estimate; Female: - 25 to 34 years: - Associate's degree` +
      num_25_34_bach_plus,
    
    num_25_64_assoc_plus = 
      `Estimate; Male: - 25 to 34 years: - Associate's degree` +
      `Estimate; Male: - 35 to 44 years: - Associate's degree` +
      `Estimate; Male: - 45 to 64 years: - Associate's degree` +
      `Estimate; Female: - 25 to 34 years: - Associate's degree` +
      `Estimate; Female: - 35 to 44 years: - Associate's degree` +
      `Estimate; Female: - 45 to 64 years: - Associate's degree` +
      num_25_64_bach_plus) %>%
  transmute(
    Id = Id,
    
    per_25_34_assoc_plus = num_25_34_assoc_plus / num_25_34 * 100,
    per_25_64_assoc_plus = num_25_64_assoc_plus / num_25_64 * 100,
    
    per_25_34_bach_plus = num_25_34_bach_plus / num_25_34 * 100,
    per_25_64_bach_plus = num_25_64_bach_plus / num_25_64 * 100,
    
    per_25_34_grad = num_25_34_grad / num_25_34 * 100,
    per_25_64_grad = num_25_64_grad / num_25_64 * 100)

map_data <- degree_map
```

```{r map3}
map_jc@data<-full_join(map_jc@data, degree_map, by = c('GEO_ID' = 'Id'))

make_map("per_25_64_bach_plus", 
         name = "Bachelor Degrees or Higher",
         legend_title = "Bachelor<br/>Degrees")

rm(degree_map)
```

## Peer City Highlights
```{r data4}
degree_poverty <- acs_time('/data/education/C17003/', starting_year = 2005)

degree_poverty %<>%
  mutate(
    total_pov = `Estimate; Income in the past 12 months below poverty level:`,
    total_nonpov = `Estimate; Income in the past 12 months at or above poverty level:`,
    
    bach_plus_per_pov = `Estimate; Income in the past 12 months below poverty level: - Bachelor's degree or higher` / total_pov * 100,
      
    bach_plus_per_nonpov = `Estimate; Income in the past 12 months at or above poverty level: - Bachelor's degree or higher` / total_nonpov * 100) %>%
    {
      x <- .
      full_join(
        x %>% weight_stl('bach_plus_per_pov', 'total_pov'),
        x %>% weight_stl('bach_plus_per_nonpov', 'total_nonpov')
      )
    }  %>%
  mutate(bach_plus_pov_gap = bach_plus_per_nonpov - bach_plus_per_pov)

data %<>% bind_df(degree_poverty)

rm(degree_poverty)
```

```{r graph4}
graph_trendline_change(data,
                'per_25_64_bach_plus',
                plot_title = 'Bachelor Degrees, Ages 25 to 64')

```

# Associate Degrees

## Ranking
```{r graph5}
rank_and_nb_group(data[data$year == 2016,], 
                  'per_25_64_assoc_plus', 
                  plot_title = 'Associate Degrees or Higher, 2016',
                  subtitle_text = 'Ages 25-64')
```

## Trendline {.tabset}

### Overall
```{r graph6.1}
graph_trendline(data,
                'per_25_64_assoc_plus',
                plot_title = 'Associate Degrees or Higher, Ages 25-64',
                rollmean = 3)
```

### By Ethnicity
```{r graph6.2}
graph_df <- data %>%
  filter(FIPS == 21111)%>%
  select(year, assoc_plus_per_white, assoc_plus_per_black, assoc_plus_per_hispanic)%>%
  mutate_at(vars( assoc_plus_per_white, assoc_plus_per_black, assoc_plus_per_hispanic), rollmean3) %>%
  gather(assoc_plus_per_white:assoc_plus_per_hispanic, 
         key = "var", value = "value")%>%
  arrange(var)

graph_df$var <- factor(graph_df$var, levels = unique(graph_df$var))

graph_trendline_race(
  graph_df,
  xmin = 2006,
  xmax = 2015,
  plot_title = "Associate Degrees or Higher by Ethnicity, Ages 25-64",
  subtitle = '3-year rolling average',
  labels = c("African American", "Hispanic", "White"),
  y_title = "Percent",
  color_pal = wes_palette("Moonrise2"))
```


# Young Adult degrees
<div style="margin-top:10px;">
</div>
## Bachelor Degrees
```{r graph7.1}
graph_trendline(data,
                'per_25_34_bach_plus',
                plot_title = 'Bachelor Degrees or Higher, Ages 25-34, 2016',
                rollmean = 3)
```

## Associate Degrees
```{r graph7.2}
graph_trendline(data,
                'per_25_34_assoc_plus',
                plot_title = 'Associate Degrees or Higher, Ages 25-34, 2016',
                rollmean = 3)
```

# Education pipeline
Waiting on private school data from the Council on Postsecondary Education

