---
title: "Jobs"
---
<div style="margin-top:50px;">
</div>
```{r "setup", include = FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/Harrison Kirby/Desktop/GLP/ccu18")
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.showtext=TRUE)
```

```{r libraries}
#Data
library(survey)
library(tidyverse)
library(magrittr)
library(feather)
library(labelled)

#Graphing
library(ggthemes)
library(classInt)
library(showtext)
library(reshape2)
library(rbokeh)
library(wesanderson)
library(kableExtra)
library(scales)

#Mapping
library(rgdal)
library(RColorBrewer)
library(leaflet)

#Make the dplyr select function the default over the plotly select function
select <- function(...){dplyr::select(...)}
```

```{r functions}
source('helper_functions.R')
```

```{r graphing}
source('graphing_functions.R')

font_add("Museo Sans 300", "MuseoSans_300.otf")
font_add("Museo Sans 300 Italic", "MuseoSans_300_Italic.otf")

#Tract Map
map_jc = readOGR('data/maps/tract', layer = "JC Tracts",
                 GDAL1_integer64_policy = TRUE, stringsAsFactors = FALSE, verbose = FALSE)

map_jc$TRACT <- as.numeric(map_jc$TRACT)

nh_names <- read_csv('data/maps/tract_to_nh.csv')

nh_names$Id2 <- substr(nh_names$Id2, 6, 13)
nh_names$Id2 <- as.numeric(nh_names$Id2)

map_jc@data <- full_join(map_jc@data, nh_names, by = c('TRACT' = 'Id2'))

map_jc@data$l_line1 <- paste("Tract #:", map_jc@data$TRACT, "in the")
map_jc@data$l_line2 <- paste(map_jc@data$Neighborhood, "neighborhood")

rm(nh_names)

#Zip Code map
map_jc_zip = readOGR('data/maps/zip', layer = 'Jefferson_County_KY_ZIP_Codes',
                     GDAL1_integer64_policy = TRUE, stringsAsFactors = FALSE, verbose = FALSE)

map_jc_zip$ZIPCODE <- as.numeric(map_jc_zip$ZIPCODE)

map_jc_zip@data$l_line1 <- paste0("Zip Code ", map_jc_zip@data$ZIPCODE)
```

```{r Website / output toggle}
web = TRUE
```

# MM: Median earnings

## 1. Ranking
```{r data9}
earn_data_05_16 <- acs_time("/data/jobs/S2001/05-16/")
earn_data_17 <- acs_time("/data/jobs/S2001/17/", starting_year = 2017)

earn_data_05_16 %<>%
  select(FIPS, 
         year,
         pop = `Total; Estimate; Population 16 years and over with earnings`,
         pop_male =`Male; Estimate; Population 16 years and over with earnings`,
         pop_female = `Female; Estimate; Population 16 years and over with earnings`,
         pop_ft = `Total; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings`,
         pop_ft_male = `Male; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings`,
         pop_ft_female = `Female; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings`,
         
         median_earnings = `Total; Estimate; Population 16 years and over with earnings - Median earnings (dollars)`,
         median_earnings_male = `Male; Estimate; Population 16 years and over with earnings - Median earnings (dollars)`,
         median_earnings_female = `Female; Estimate; Population 16 years and over with earnings - Median earnings (dollars)`,
         median_earnings_ft = `Total; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings - Mean earnings (dollars)`,
         median_earnings_ft_male = `Male; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings - Median earnings (dollars)`,
         median_earnings_ft_female = `Female; Estimate; Population 16 years and over with earnings - Full-time, year-round workers with earnings - Median earnings (dollars)`) %>%
  mutate_at(vars(pop, pop_male, pop_female, pop_ft, pop_ft_male, pop_ft_female, 
              median_earnings, median_earnings_male, median_earnings_female,
              median_earnings_ft, median_earnings_ft_male, median_earnings_ft_female),
            as.numeric)

earn_data_17 %<>%
  select(FIPS, 
         year,
         pop = `Total; Estimate; Population 16 years and over with earnings`,
         pop_male =`Male; Estimate; Population 16 years and over with earnings`,
         pop_female = `Female; Estimate; Population 16 years and over with earnings`,
         pop_ft = `Total; Estimate; FULL-TIME, YEAR-ROUND WORKERS WITH EARNINGS`,
         pop_ft_male = `Male; Estimate; FULL-TIME, YEAR-ROUND WORKERS WITH EARNINGS`,
         pop_ft_female = `Female; Estimate; FULL-TIME, YEAR-ROUND WORKERS WITH EARNINGS`,
         
         median_earnings = `Total; Estimate; Median earnings (dollars)`,
         median_earnings_male = `Male; Estimate; Median earnings (dollars)`,
         median_earnings_female = `Female; Estimate; Median earnings (dollars)`,
         median_earnings_ft = `Total; Estimate; Median earnings (dollars) for full-time, year-round workers with earnings`,
         median_earnings_ft_male = `Male; Estimate; Mean earnings (dollars) for full-time, year-round workers with earnings`,
         median_earnings_ft_female = `Female; Estimate; Mean earnings (dollars) for full-time, year-round workers with earnings`) %>%
  mutate_at(vars(pop, pop_male, pop_female, pop_ft, pop_ft_male, pop_ft_female, 
              median_earnings, median_earnings_male, median_earnings_female,
              median_earnings_ft, median_earnings_ft_male, median_earnings_ft_female),
            as.numeric)

earn_data <- bind_rows(earn_data_05_16, earn_data_17)

earn_data <- bind_df(
  earn_data %>% weight_stl("median_earnings", "pop"),
  earn_data %>% weight_stl("median_earnings_male", "pop_male"),
  earn_data %>% weight_stl("median_earnings_female", "pop_female"),
  earn_data %>% weight_stl("median_earnings_ft", "pop_ft"),
  earn_data %>% weight_stl("median_earnings_ft_male", "pop_ft_male"),
  earn_data %>% weight_stl("median_earnings_ft_female", "pop_ft_female"))

data <- earn_data

data %<>% pull_peers_FIPS() %>% select(FIPS, city, year, current, baseline, everything())

rm(earn_data_05_16, earn_data_17, earn_data)
```

```{r MSA counties, eval = FALSE}
acs_time2 <- function(folder, starting_year = 2005){
  wd <- getwd()
  directory <- paste0(wd, folder)
  file_names <- list.files(directory)
  n <- length(file_names)
  y <- starting_year
  for (i in 1:n){
    file_path <- paste0(wd, folder, file_names[i])
    data <- read_csv(file_path, skip=1, col_types = cols("Id2" = col_double()))
    names(data)[names(data) == 'Id2'] <- 'FIPS'
    all_peers <- data
    all_peers$year <- y
    y <- y + 1
    
    if(i == 1){
      df <- all_peers 
    }
    else{
      names(all_peers) <- names(df)
      df <- rbind(df, all_peers)
    }
  }
  df
}


earn_data <- acs_time2("/med_inc/")

`%!in%` <- negate(`%in%`)

earn_data %<>%
  filter(FIPS %!in% c(1073, 12031, 18097, 21111, 26081, 29095, 31055, 37081, 37119, 37183, 39049, 39061, 39113, 40109, 40143, 45045, 47037, 47093, 47157, 51760, 29189, 29510))

earn_data$FIPS[earn_data$FIPS %in% c(26015, 26081, 26117, 26139)] <- 26081
earn_data$FIPS[earn_data$FIPS %in% c(17005, 17013, 17027, 17083, 17117, 17119, 17133, 17163, 29071, 29099, 29113, 29183, 29189, 29510, 29219)] <- "MERGED"
earn_data$FIPS[earn_data$FIPS %in% c(40017, 40027, 40051, 40081, 40083, 40087, 40109)] <- 40109
earn_data$FIPS[earn_data$FIPS %in% c(40037, 40111, 40113, 40117, 40131, 40143, 40145)] <- 40143
earn_data$FIPS[earn_data$FIPS %in% c(45007, 45045, 45059, 45077)] <- 45045
earn_data$FIPS[earn_data$FIPS %in% c(47001, 47009, 47013, 47057, 47093, 47105, 47129, 47145, 47173)] <- 47093
earn_data$FIPS[earn_data$FIPS %in% c(1007, 1009, 1021, 1073, 1115, 1117, 1127)] <- 1073
earn_data$FIPS[earn_data$FIPS %in% c(18019, 18043, 18061, 18143, 18175, 21029, 21103, 21111, 21185, 21211, 21215, 21223)] <- 21111
earn_data$FIPS[earn_data$FIPS %in% c(18011, 18013, 18057, 18059, 18063, 18081, 18095, 18097, 18109, 18133, 18145)] <- 18097
earn_data$FIPS[earn_data$FIPS %in% c(20091, 20103, 20107, 20121, 20209, 29013, 29025, 29037, 29047, 29049, 29095, 29107, 29165, 29177)] <- 29095
earn_data$FIPS[earn_data$FIPS %in% c(19085, 19129, 19155, 31025, 31055, 31153, 31155, 31177)] <- 31055
earn_data$FIPS[earn_data$FIPS %in% c(37081, 37151, 37157)] <- 37081
earn_data$FIPS[earn_data$FIPS %in% c(37025, 37071, 37097, 37109, 37119, 37159, 37167, 37179, 45023, 45057, 45091)] <- 37119
earn_data$FIPS[earn_data$FIPS %in% c(39041, 39045, 39049, 39073, 39089, 39097, 39117, 39127, 39129, 39159)] <- 39049
earn_data$FIPS[earn_data$FIPS %in% c(18029, 18115, 18161, 21015, 21023, 21037, 21077, 21081, 21117, 21191, 39015, 39017, 39025, 39061, 39165)] <- 39061
earn_data$FIPS[earn_data$FIPS %in% c(47015, 47021, 47037, 47043, 47081, 47111, 47119, 47147, 47149, 47159, 47165, 47169, 47187, 47189)] <- 47037
earn_data$FIPS[earn_data$FIPS %in% c(5035, 28009, 28033, 28093, 28137, 28143, 47047, 47157, 47167)] <- 47157
earn_data$FIPS[earn_data$FIPS %in% c(12003, 12019, 12031, 12089, 12109)] <- 12031
earn_data$FIPS[earn_data$FIPS %in% c(37069, 37101, 37183)] <- 37183
earn_data$FIPS[earn_data$FIPS %in% c(39057, 39109, 39113)] <- 39113
earn_data$FIPS[earn_data$FIPS %in% c(51007, 51033, 51036, 51041, 51570, 51053, 51075, 51085, 51087, 51670, 51101, 51127, 51730, 51145, 51149, 51760, 51183)] <- 51760

earn_data %<>% pull_peers_FIPS()

earn_data <- earn_data %>%
  select(FIPS,
         median_earnings = `Total; Estimate; Median earnings (dollars)`,
         pop = `Total; Estimate; Population 16 years and over with earnings`) %>%
  mutate(median_earnings = as.numeric(as.character(median_earnings)),
         FIPS = as.character(FIPS)) %>%
  group_by(FIPS) %>%
  summarise(median_earnings = weighted.mean(median_earnings, pop)) %>%
  ungroup() %>%
  mutate(year = 2014)

data <- earn_data

data %<>% pull_peers_FIPS() %>% select(FIPS, city, year, current, baseline, everything())

rm(earn_data)
```

```{r MSA total, eval = FALSE}
earn_data <- readxl::read_xlsx("MSA_M2017_dl.xlsx")

earn_data %<>%
  filter(OCC_CODE == "00-0000") %>%
  transmute(
    MSA = as.numeric(AREA),
    median_earnings = as.numeric(A_MEDIAN),
    year = 2016) %>%
  pull_peers_MSA() 

add_FIPS_to_MSA <- function(data){
  
  data$FIPS<-NA
  data$FIPS[data$MSA == 24340] = 26081
  data$FIPS[data$MSA == 41180] = 'MERGED'
  data$FIPS[data$MSA == 36420] = 40109
  data$FIPS[data$MSA == 46140] = 40143
  data$FIPS[data$MSA == 24860] = 45045
  data$FIPS[data$MSA == 28940] = 47093
  data$FIPS[data$MSA == 13820] = 1073
  data$FIPS[data$MSA == 31140] = 21111
  data$FIPS[data$MSA == 26900] = 18097
  data$FIPS[data$MSA == 28140] = 29095
  data$FIPS[data$MSA == 36540] = 31055
  data$FIPS[data$MSA == 24660] = 37081
  data$FIPS[data$MSA == 16740] = 37119
  data$FIPS[data$MSA == 18140] = 39049
  data$FIPS[data$MSA == 17140] = 39061
  data$FIPS[data$MSA == 34980] = 47037
  data$FIPS[data$MSA == 32820] = 47157
  data$FIPS[data$MSA == 27260] = 12031
  data$FIPS[data$MSA == 39580] = 37183
  data$FIPS[data$MSA == 19380] = 39113
  data$FIPS[data$MSA == 40060] = 51760
  
  data
}

earn_data %<>% add_FIPS_to_MSA()

data <- earn_data

data %<>% pull_peers_FIPS() %>% select(FIPS, city, year, current, baseline, everything())

rm(earn_data)
```

```{r}
rpp <- read_csv("data/jobs/rppmsa.csv", skip = 4, col_names = TRUE, na = c("", "(NA)"))

rpp$`2005` <- rpp$`2008`
rpp$`2006` <- rpp$`2008`
rpp$`2007` <- rpp$`2008`
rpp$`2016` <- rpp$`2015`
rpp$`2017` <- rpp$`2015`

rpp <- rpp %>%
  filter(LineCode == 4) %>%
  select(-GeoFips, -LineCode, -Description) %>%
  gather(2:14, key = year, value = "rpp") %>%
  mutate(year = as.numeric(year))

rpp$MSA <- substr(rpp$GeoName, 0, unlist(gregexpr(pattern = " \\(", rpp$GeoName)) -1 )

rpp$MSA[rpp$MSA == "Grand Rapids-Wyoming, MI"] = "Grand Rapids"
rpp$MSA[rpp$MSA == "St. Louis, MO-IL"] = "St. Louis"
rpp$MSA[rpp$MSA == "Oklahoma City, OK"] = "Oklahoma City"
rpp$MSA[rpp$MSA == "Tulsa, OK"] = "Tulsa"
rpp$MSA[rpp$MSA == "Greenville-Anderson-Mauldin, SC"] = "Greenville"
rpp$MSA[rpp$MSA == "Knoxville, TN"] = "Knoxville"
rpp$MSA[rpp$MSA == "Birmingham-Hoover, AL"] = "Birmingham"
rpp$MSA[rpp$MSA == "Louisville/Jefferson County, KY-IN"] = "Louisville"
rpp$MSA[rpp$MSA == "Indianapolis-Carmel-Anderson, IN"] = "Indianapolis"
rpp$MSA[rpp$MSA == "Kansas City, MO-KS"] = "Kansas City"
rpp$MSA[rpp$MSA == "Omaha-Council Bluffs, NE-IA"] = "Omaha"
rpp$MSA[rpp$MSA == "Greensboro-High Point, NC"] = "Greensboro"
rpp$MSA[rpp$MSA == "Charlotte-Concord-Gastonia, NC-SC"] = "Charlotte"
rpp$MSA[rpp$MSA == "Columbus, OH"] = "Columbus"
rpp$MSA[rpp$MSA == "Cincinnati, OH-KY-IN"] = "Cincinnati"
rpp$MSA[rpp$MSA == "Nashville-Davidson--Murfreesboro--Franklin, TN"] = "Nashville"
rpp$MSA[rpp$MSA == "Memphis, TN-MS-AR"] = "Memphis"
rpp$MSA[rpp$MSA == "Jacksonville, FL"] = "Jacksonville"
rpp$MSA[rpp$MSA == "Raleigh, NC"] = "Raleigh"
rpp$MSA[rpp$MSA == "Dayton, OH"] = "Dayton"
rpp$MSA[rpp$MSA == "Richmond, VA"] = "Richmond"

rpp %<>% select(-GeoName)

data %<>% left_join(rpp, by = c('year' = 'year', 'city' = 'MSA'))

data %<>%
  group_by(year) %>%
  mutate(rpp_lou = rpp[city == "Louisville"],
         rpp_index = rpp_lou / rpp) %>%
  ungroup() %>%
  select(-rpp, -rpp_lou)

cpi <- read_csv("data/jobs/CPI-U-RS.csv")

cpi %<>%
  rename(year = YEAR,
         cpi = AVG)

data %<>% left_join(cpi, by = "year")

data %<>%
  group_by(city) %>%
  mutate(base_cpi = cpi[year == 2017],
         cpi_index = base_cpi/cpi) %>%
  ungroup() %>%
  select(-cpi, -base_cpi)

rpp_col_adj <- function(x){
  x *  data$rpp_index * data$cpi_index
}

data %<>% mutate_at(vars(median_earnings, median_earnings_male, median_earnings_female, 
                         median_earnings_ft, median_earnings_ft_male, median_earnings_ft_female), rpp_col_adj)

rm(rpp, cpi)
```

```{r graph9}
rank_and_nb_group(data[data$year == 2017,], 
                  'median_earnings',
                  plot_title = 'Median Earnings, 2017')
```

## 2. Trendline
```{r data10}
earn_data_white <- acs_time("/data/jobs/B20017H/")

earn_data_white <- earn_data_white %>%
  select(FIPS, 
         year,
         median_earnings_white = `Estimate; Total:`) %>%
  mutate(FIPS = as.character(FIPS),
         median_earnings_white = as.numeric(as.character(median_earnings_white))) %>%
  weight_stl('median_earnings_white')

earn_data_black <- acs_time("/data/jobs/B20017B/")

earn_data_black <- earn_data_black %>%
  select(FIPS, 
         year,
         median_earnings_black = `Estimate; Total:`) %>%
  mutate(FIPS = as.character(FIPS),
         median_earnings_black = as.numeric(as.character(median_earnings_black))) %>%
  weight_stl('median_earnings_black')

earn_data_hisp <- acs_time("/data/jobs/B20017I/")

earn_data_hisp <- earn_data_hisp %>%
  select(FIPS, 
         year,
         median_earnings_hispanic = `Estimate; Total:`) %>%
  mutate(FIPS = as.character(FIPS),
         median_earnings_hispanic = as.numeric(as.character(median_earnings_hispanic))) %>%
  weight_stl('median_earnings_hispanic')

data %<>% bind_df(earn_data_white, earn_data_black, earn_data_hisp) %>%
  mutate_at(vars(median_earnings_white, median_earnings_black, median_earnings_hispanic), rpp_col_adj)

rm(earn_data_white, earn_data_black, earn_data_hisp)
```

```{r graph 10.1}
graph_trendline(data,
                'median_earnings',
                plot_title = 'Median Earnings',
                y_title = 'Dollars',
                xmax = 2017)
```

## 3. Map
```{r data11}
earn_map <- read_csv("data/jobs/ACS_16_5YR_S2001_with_ann.csv", skip = 1,
                      col_types = cols(
                      `Total; Estimate; Median earnings (dollars)` = col_number())
                   ) 

earn_map %<>% select(Id, median_earnings = `Total; Estimate; Median earnings (dollars)`)
```

```{r graph11}
map_jc@data <- full_join(map_jc@data, earn_map, by = c('GEO_ID' = 'Id'))

make_map("median_earnings", 
         name = "Median Earnings",
         legend_title = "Median<br/>Earnings",
         units = "Dollars")

rm(earn_map)
```

## 4. Peer Growth

```{r graph4}
graph_trendline_change(
  data,
  'median_earnings',
  plot_title = "Median Earnings",
  xmax = 2017)
```

## 5. By Race

```{r graph 10.3}
graph_trendline_race_peer(data, 
                          vars = c('median_earnings_white', 'median_earnings_black', 'median_earnings_hispanic'),
                          plot_title = 'Median Earnings by Ethnicity',
                          rollmean = 3,
                          y_title = 'Dollars',
                          xmax = 2017)
```

## 6. By Gender
```{r}
graph_trendline_race_peer_two(
  data, 
  vars = c('median_earnings_male', 'median_earnings_female'),
  cat_labels = c("Male","Female"),
  plot_title = "Median Earnings by Gender",
  y_title = "Dollars",
  xmax = 2017)

data %<>%
  mutate(wage_gap = median_earnings_female / median_earnings_male * 100)

graph_trendline(
  data,
  "wage_gap",
  plot_title = "Wage Gap: Males and Females",
  y_title = "Percent",
  rollmean = 5,
  xmax = 2017)

```

# Earnings Gap

## 1. Black and White Residents
```{r data13}
data %<>%
  mutate(earnings_gap_black = median_earnings_white - median_earnings_black,
         earnings_gap_hispanic = median_earnings_white - median_earnings_hispanic)
```

## 2. Hispanic and White Residents
```{r graph13}
graph_trendline(data,
                'earnings_gap_black',
                plot_title = 'Earnings Gap: Black and White Residents',
                y_title = "Dollars",
                rollmean = 5,
                xmax = 2017)

graph_trendline(data,
                'earnings_gap_hispanic',
                plot_title = 'Earnings Gap: Hispanic and White Residents',
                y_title = "Dollars",
                rollmean = 5,
                xmax = 2017)
```

# Job Distribution
```{r data14}
business_data <- business_time('/data/jobs/CBP/')

#Join to Louisville Zip codes
zip_codes <- read_csv('data/jobs/zcta_county_rel_10.csv')

zip_codes %<>% 
  filter(GEOID == 21111) %>%
  select(zip = ZCTA5,
         pop = ZPOP)

zip_codes$pop[zip_codes$zip == 40231] <- NA

business_data <- zip_codes %>% 
  left_join(business_data, by = c('zip' = 'Id2'))

business_data %<>%
  mutate(businesses_per_resident = businesses / pop,
         jobs_per_resident = employees / pop,
         payroll_per_resident = payroll / pop,
         payroll_per_job = payroll / employees) %>%
  select(zip, year, pop,
         businesses_per_resident, jobs_per_resident, payroll_per_resident, payroll_per_job)

business_data_change <- business_data %>%
  group_by(zip) %>%
  mutate(businesses_per_resident_change = (businesses_per_resident - first(businesses_per_resident)) / first(businesses_per_resident) * 100,
         jobs_per_resident_change = (jobs_per_resident - first(jobs_per_resident)) / first(jobs_per_resident) * 100,
         payroll_per_resident_change = (payroll_per_resident - first(payroll_per_resident)) / first(payroll_per_resident) * 100,
         payroll_per_job_change = (payroll_per_job - first(payroll_per_job)) / first(payroll_per_job) * 100) %>%
  mutate_at(vars(businesses_per_resident_change, jobs_per_resident_change, payroll_per_resident_change, payroll_per_job_change), mean, na.rm = TRUE) %>%
  ungroup() %>%
  select(
    zip, year,
    businesses_per_resident_change, jobs_per_resident_change, payroll_per_resident_change, payroll_per_job_change) %>%
  filter(year == 2016)

business_data_change_5yr <- business_data %>%
  filter(year > 2011) %>%
  group_by(zip) %>%
  mutate(businesses_per_resident_change_5yr = (businesses_per_resident - first(businesses_per_resident)) / first(businesses_per_resident) * 100,
         jobs_per_resident_change_5yr = (jobs_per_resident - first(jobs_per_resident)) / first(jobs_per_resident) * 100,
         payroll_per_resident_change_5yr = (payroll_per_resident - first(payroll_per_resident)) / first(payroll_per_resident) * 100,
         payroll_per_job_change_5yr = (payroll_per_job - first(payroll_per_job)) / first(payroll_per_job) * 100) %>%
  mutate_at(vars(businesses_per_resident_change_5yr, jobs_per_resident_change_5yr, payroll_per_resident_change_5yr, payroll_per_job_change_5yr), mean, na.rm = TRUE) %>%
  ungroup() %>%
  select(
    zip, year,
    businesses_per_resident_change_5yr, jobs_per_resident_change_5yr, payroll_per_resident_change_5yr, payroll_per_job_change_5yr) %>%
  filter(year == 2016)

business_data %<>% left_join(business_data_change, by = c('zip', 'year')) %>% left_join(business_data_change_5yr, by = c('zip', 'year'))

business_data$businesses_per_resident[business_data$zip %in% c(40202, 40215, 40209, 40220)] <- NA
business_data$jobs_per_resident[business_data$zip %in% c(40202, 40215, 40209, 40220)] <- NA
business_data$payroll_per_resident[business_data$zip %in% c(40202, 40215, 40209, 40220)] <- NA
business_data$payroll_per_job[business_data$zip %in% c(40202, 40215, 40209, 40220)] <- NA

map_data_zip <- business_data %>% filter(year == 2016)

rm(zip_codes, business_data)

#a = 0-19
#e = 250-499
#g = 1,000 to 2,499
```

```{r graph14}
map_jc_zip@data %<>% left_join(map_data_zip, by = c('ZIPCODE' = 'zip'))
```

## 5. Jobs per Resident
```{r graph14.2}
make_map_zip("jobs_per_resident", 
             name = "Jobs per Resident",
             legend_title = "Jobs<br/>per res",
             units = "none",
             map_style = "sequential")
```

## 6. Jobs per Resident Change
```{r}
make_map_zip("jobs_per_resident_change_5yr", 
             name = "Jobs per Resident",
             legend_title = "Jobs<br/>per res",
             units = "Percent",
             map_style = "divergent")
```

# Unemployment

```{r graph15.1}
unemp <- unemployment_time("/data/jobs/unemployment/")

unemp %<>%
  mutate(FIPS = paste0(stateFIPS, countyFIPS),
         FIPS = as.character(as.numeric(FIPS))) %>%
  select(FIPS, year, unemp_rate) %>%
  pull_peers_FIPS(add_info = FALSE)

unemp18 <- read_csv('data/jobs/unemployment18.csv', skip = 2)

unemp18 %<>% 
  filter(year == 2018) %>%
  select(FIPS, unemp_rate) %>%
  group_by(FIPS) %>%
  summarise(unemp_rate = mean(unemp_rate)) %>%
  ungroup() %>%
  mutate(year = 2018,
         FIPS = as.character(as.numeric(FIPS))) %>%
  pull_peers_FIPS(add_info = FALSE)

unemp <- bind_rows(unemp, unemp18) %>% weight_stl("unemp_rate") 

data %<>% bind_df(unemp) %>% select(-city, -baseline, -current) %>% pull_peers_FIPS()

```

## 7. Ranking
```{r graph 15.1}
rank_and_nb_group(data[data$year == 2018,], 
                  'unemp_rate', 
                  plot_title = 'Unemployment, 2018',
                  order = "Ascending")
```

## 8. Trendline
```{r}
graph_trendline(data,
                'unemp_rate',
                xmin = 2000,
                xmax = 2018,
                plot_title = 'Unemployment')
```

## 9. By Race
```{r data15.1}
#White
unemp_white <- acs_time("/data/jobs/B23002H/", starting_year = 2005)

unemp_white %<>%
  mutate(
    total = 
      `Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 65 to 69 years: - In labor force:` +
      `Estimate; Male: - 70 years and over: - In labor force:` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 65 to 69 years: - In labor force:` +
      `Estimate; Female: - 70 years and over: - In labor force:`,
    
    unemp_white = 
      (`Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Male: - 70 years and over: - In labor force: - Unemployed` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Female: - 70 years and over: - In labor force: - Unemployed`)
      / total * 100) %>%
  weight_stl('unemp_white', 'total')

#Black
unemp_black <- acs_time("/data/jobs/B23002B/", starting_year = 2005)

unemp_black %<>%
  mutate(
    total = 
      `Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 65 to 69 years: - In labor force:` +
      `Estimate; Male: - 70 years and over: - In labor force:` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 65 to 69 years: - In labor force:` +
      `Estimate; Female: - 70 years and over: - In labor force:`,
    
    unemp_black = 
      (`Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Male: - 70 years and over: - In labor force: - Unemployed` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Female: - 70 years and over: - In labor force: - Unemployed`)
      / total * 100) %>%
  weight_stl('unemp_black', 'total')

#Hispanic
unemp_hisp <- acs_time("/data/jobs/B23002I/", starting_year = 2006)

unemp_hisp %<>%
  mutate(
    total = 
      `Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 65 to 69 years: - In labor force:` +
      `Estimate; Male: - 70 years and over: - In labor force:` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 65 to 69 years: - In labor force:` +
      `Estimate; Female: - 70 years and over: - In labor force:`,
    
    unemp_hisp = 
      (`Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Male: - 70 years and over: - In labor force: - Unemployed` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Female: - 70 years and over: - In labor force: - Unemployed`)
      / total * 100) %>%
  weight_stl('unemp_hisp', 'total')

data %<>% bind_df(unemp_white, unemp_black, unemp_hisp)

rm(unemp_white, unemp_black, unemp_hisp)

```

```{r data15.2}
#Hispanic
unemp_hisp <- acs_time("/data/jobs/B23002-3year/B23002I/", starting_year = 2006)

unemp_hisp %<>%
  mutate(
    total = 
      `Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Male: - 65 to 69 years: - In labor force:` +
      `Estimate; Male: - 70 years and over: - In labor force:` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian:` +
      `Estimate; Female: - 65 to 69 years: - In labor force:` +
      `Estimate; Female: - 70 years and over: - In labor force:`,
    
    unemp_hisp_3 = 
      (`Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Male: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Male: - 70 years and over: - In labor force: - Unemployed` +
      `Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 20 to 24 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 25 to 54 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 55 to 64 years: - In labor force: - Civilian: - Unemployed` +
      `Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed` + 
      `Estimate; Female: - 70 years and over: - In labor force: - Unemployed`)
      / total * 100) %>%
  weight_stl('unemp_hisp_3', 'total')

data %<>% bind_df(unemp_hisp)

rm(unemp_hisp)

```

```{r graph15}
xmin <- 2005
xmax <- 2017
df <- data
rollmean <- 3

#create a new variable to use var with the '$' operator
df$var_white <- df$unemp_white
df$var_black <- df$unemp_black
df$var_hisp  <- df$unemp_hisp_3

df.wol <- subset(df,current == 1 & FIPS!=21111)

#calculate 25th and 75th percentiles
output_wol = df %>% 
  group_by(year) %>%
  summarise(
    white_q1   = quantile(var_white, prob = 0.25, na.rm = TRUE),
    white_mean = mean(var_white, na.rm = TRUE),
    white_q3   = quantile(var_white, prob = 0.75, na.rm = TRUE),
    black_q1   = quantile(var_black, prob = 0.25, na.rm = TRUE),
    black_mean = mean(var_black, na.rm = TRUE),
    black_q3    = quantile(var_black, prob = 0.75, na.rm = TRUE),
    hisp_q1    = quantile(var_hisp, prob = 0.25, na.rm = TRUE),
    hisp_mean  = mean(var_hisp, na.rm = TRUE),
    hisp_q3    = quantile(var_hisp, prob = 0.75, na.rm = TRUE))

#extract Louisville values
lville = df %>% 
  filter(FIPS == 21111) %>% 
  select(var_white, var_black, var_hisp, year)

#join 25th percentile, 75th percentile, and Louisville values
dat = full_join(lville, output_wol, by = "year")

if(xmin == 2000 & rollmean == 3){
  var_2000 <- dat$var[dat$year == 2000]
  first_quarter_2000 <- dat$first_quarter[dat$year == 2000]
  mean_2000 <- dat$mean[dat$year == 2000]
  third_quarter_2000 <- dat$third_quarter[dat$year == 2000]
}

#Calculate 3-year rolling average
dat <- dat %>%
  mutate_at(vars(var_white, var_black,
            white_q1, white_mean, white_q3,
            black_q1, black_mean, black_q3), rollmean3)
  if(xmin != 2000){
    dat <- dat %>% filter((year > xmin))
    xmin = xmin +1
  }
  
  dat <- dat %>% filter((year < xmax))
  xmax = xmax -1
  subtitle_text = "3-year rolling average"

if(xmin == 2000 & rollmean == 3){
  dat$var[dat$year == 2000] <- var_2000
  dat$first_quarter[dat$year == 2000] <- first_quarter_2000
  dat$mean[dat$year == 2000] <- mean_2000
  dat$third_quarter[dat$year == 2000] <- third_quarter_2000
}

#set x-axis labels based on break_settings parameter
if(xmax - xmin > 5){
  skip = 2
}else{
  skip = 1
}

if((xmax - xmin) %% 2 == 0 || skip == 1){
  break_settings = seq(xmin, xmax, skip)
} else{
  break_settings = seq(xmin + 1, xmax, skip)
}

#reshape data
data_long <- melt(dat, id="year")
data_long <- data_long[!is.na(data_long$value),]

data_long$race[data_long$variable %in% c('var_white', 'white_q1', 'white_mean', 'white_q3')] <- "White"
data_long$race[data_long$variable %in% c('var_black', 'black_q1', 'black_mean', 'black_q3')] <- "Black"
data_long$race[data_long$variable %in% c('var_hisp', 'hisp_q1', 'hisp_mean', 'hisp_q3')] <- "Hispanic"

#initial line plot
p <- ggplot(data=data_long,aes(x=year, y=value, color = variable, linetype = variable, alpha = variable))+
  geom_point(size = 1.8)+
  geom_line(size = 1, aes(group = variable))
p <- p + theme_bw()
midpoint <- (max(data_long$value, na.rm = TRUE)+min(data_long$value, na.rm = TRUE))/2
border_space <- .1 * midpoint
p <- p + ylim(c(min(data_long$value, na.rm = TRUE) - border_space, max(data_long$value, na.rm=TRUE) + border_space))
p<-p+scale_x_continuous(limits = c(xmin, xmax), breaks = break_settings)
p<-p+scale_y_continuous(labels = comma)

#var_white var_black var_hisp white_q1 white_mean white_q3 black_q1 black_mean blackq3 hisp_q1 hisp_mean hisp_q3

#add color and line types
cPalette <- c('blue', 'red', 'darkgreen',
              "black", "blue", "black",
              "black", "red", "black",
              "black", "darkgreen", "black")
p <- p + 
  scale_colour_manual(
    values = cPalette)

 p <- p + scale_linetype_manual(
   values = c("solid", "solid", "solid",
              "dashed", "dashed", "dashed",
              "dashed", "dashed", "dashed",
              "dashed", "dashed", "dashed"))
 
 p <- p + scale_alpha_manual(
   values = c(1, 1, 1, 0, .8, 0,
              0, .8, 0, 0, .8, 0))

#add remaining style and elements
p<-p+theme(text = element_text(family = "Museo Sans 300"),
           legend.title=element_blank(),
           legend.position = "top",
           axis.text=element_text(size=24, family = "Museo Sans 300"),
           axis.title = element_text(size = 24),
           axis.ticks.y=element_blank(),
           plot.title=element_text(size=36, hjust=.5, family = "Museo Sans 300",
                                   margin=margin(b=10,unit="pt")),
           legend.text=element_text(size=24, family = "Museo Sans 300"),
           plot.caption = element_text(family = "Museo Sans 300"),
           plot.subtitle = element_text(family = "Museo Sans 300", hjust = 0.5, size = 20))

p<-p+labs(title = "Median Earnings by Race", 
          x = "Year",
          y = "Percent", 
          caption = "", 
          subtitle = subtitle_text)

ribbon_dat <- data_long %>% 
  filter(variable %in% c('white_q1', 'black_q1', 'hisp_q1', 'white_q3', 'black_q3', 'hisp_q3'))

positions <- data.frame(
  variable = ribbon_dat$variable,
  race = ribbon_dat$race,
  x  = ribbon_dat$year,
  y  = ribbon_dat$value)

positions <- positions %>% 
{
  x <- .
  bind_rows(
    x %>% filter(variable %in% c('white_q1', 'black_q1', 'hisp_q1')),
    x %>% filter(variable %in% c('white_q3', 'black_q3', 'hisp_q3')) %>% arrange(desc(x)))
}

p <- p + geom_polygon(data = positions, 
                      aes(x = x, y = y, group = race, fill = factor(race), color = factor(race)), 
                      col = NA, alpha = 0.3)

#p <- p + scale_fill_manual(values = c('#7fc97f', '#beaed4', '#fdc086'))

p <- p + guides(linetype = FALSE, color = FALSE, alpha = FALSE)

p

```